services:
  busca-cep-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: greglixandrao/busca-cep-api:latest
    container_name: busca-cep-backend
    ports:
      - "8001:8000"
    environment:
      - APP_NAME=API de Busca de CEP
      - APP_VERSION=1.0.0
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
      - VIACEP_BASE_URL=https://viacep.com.br/ws
      - VIACEP_TIMEOUT=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - busca-cep-network

  # Opcional: Nginx como proxy reverso (descomente se necessário)
  # nginx:
  #   image: nginx:alpine
  #   container_name: busca-cep-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - busca-cep-api
  #   restart: unless-stopped
  #   networks:
  #     - busca-cep-network

networks:
  busca-cep-network:
    driver: bridge
